### ISSUE TITLE
enhancement: drop encoding workarounds

### ISSUE THREAD

**Issue by drzraf** [bcrowell/when#11]
Almost 350 lines of code are related to accents handling/transformation. Why?
In an UTF-8 world, it's a problem of the past.

Related or not, I note that there is (or used to be) inconsistency in translations input encoding.
An example:
``egrep "'fr|'el" /usr/bin/when|head -2``
```
   'fr'=>"Jan F${e_acute}v Mar Avr Mai Juin Juil Ao${u_circumflex} Sep Oct Nov D${e_acute}c", # French
   'el'=>'Ιαν Φεβ Μαρ Απρ Μάι Ιούν Ιούλ Αύγ Σεπ Οκτ Νοέ Δεκ', # Greek
```
While greek is just plain simple UTF-8 which (I guess) works flawlessly, french contains named entities. And the variables contain the  hex codes corresponding to ... LATIN-9 (ISO8859-15) encoding. Why?

I still have difficulties understanding why the program would need to transform it's output according to the TERM it's running into. Even the most basic "linux" TERM (non-virtual tty) does display french accents correctly.

Giving the possibility to input months with or without accent is a nice point, but the perl iconv library would be easier in this regard.
For example, currently if french month names where to be switched to UTF-8, the home-made UTF-8 transliterator (``filter_out_accents``) would have to be modified to make the substitution for UTF-8 hex rather than Latin-9.

I don't know about OS/platform/perl-version requisites but, although I **really do like how self-contained ``when`` is**, don't you think depending upon either Text::Unidecode or Text::Iconv could definitely help working out this encoding issue?

**Comment by bcrowell** [comment]
One of the basic design decisions in when was that it would not require any external libraries at all. The filtering is based on real-world experience with terminals that don't display the characters properly.
