### ISSUE TITLE
when: fails with Perl 5.24: Invalid range "y-a" in transliteration operator

### ISSUE THREAD

**Issue by carnil** [bcrowell/when#12]
Hi,

We have the following bug reported to the Debian package of when
(https://bugs.debian.org/825955):

It doesn't seem to be a bug in the packaging, so you may want to take
a look. Actually when fails when used with Perl 5.24.

------8<-----------8<-----------8<-----------8<-----------8<-----

```
Package: when
Version: 1.1.35-1
Severity: important
User: debian-perl@lists.debian.org
Usertags: perl-5.24-transition

This package fails to build with Perl 5.24 (currently in experimental.)
  
  pod2man --section=1 --center="When `perl when --bare_version`" --release="`perl when --bare_version`" \
          --name=WHEN <when >when.1
  Invalid range "y-a" in transliteration operator at when line 2821.
  Invalid range "y-a" in transliteration operator at when line 2821.
  Option release requires an argument
  Makefile:83: recipe for target 'when.1' failed
  make[1]: *** [when.1] Error 1

A full build log is available at
  http://perl.debian.net/rebuild-logs/perl-5.24-throwaway/when_1.1.35-1/

-- 
Niko Tyni   ntyni@debian.org


```
------8<-----------8<-----------8<-----------8<-----------8<-----

Thanks for considering,
  Salvatore Bonaccorso,
  Debian Perl Group

**Comment by bcrowell** [comment]
Thanks for letting me know about that. The error was caused by code that was inactive anyhow, so I removed it. I've released When 1.1.36, which should fix this problem.
