### ISSUE TITLE
feature request: color per item

### ISSUE THREAD

**Issue by drzraf** [bcrowell/when#13]
When having more than a couple of recurring events, colors help getting significant events visible among others.
Something simple like adding #yellow, #blue ... to the event text and getting it interpreted to color shell output could make the difference.
What do you think?

**Comment by bcrowell** [comment]
I would prefer to find a way to make this functionality available without adding more code to When. It seems like it could be done with some kind of post-filtering through some other program. My general design concept for When is that it's supposed to be ridiculously simple.

**Comment by drzraf** [comment]
Just did it then aliased `when` to `command when | tag-color`
That did the trick.
