### ISSUE TITLE
Option --rows is interpreted as --rows_auto

### ISSUE THREAD

**Issue by Garmelon** [bcrowell/when#15]
When attempting to use --rows, an error message about rows_auto not taking any arguments is shown:
```
$ when --rows=10
Option rows_auto does not take an argument
```

By the way, the man page says `--rows=COLUMNS`.

**Comment by bcrowell** [comment]
Thanks for pointing out the bug. It's fixed in version 1.1.37. I've also fixed the error in the man page and added a note explaining that when using this option, you will also normally need to do a --norows_auto.
