### ISSUE TITLE
Feature Request: Day after specified

### ISSUE THREAD

**Issue by Mrfiregem** [bcrowell/when#17]
I want to put in my calendar Black Friday in my calendar, but I'm having trouble making a formula to track it.

I've tried `m=nov & w=fri & a=4` since it's the day after Thanksgiving, but this year (2019), the 4th Friday is a week before the 4th Wednesday. There may be some way using `j`, but I can't figure it out, which is why I suggest an adding function, e.g. `(m=nov & w=thu & a=4)+1` or something similar.

**Comment by bcrowell** [comment]
This is a totally reasonable thing to want to do, but I think it would be pretty nontrivial to implement, given the very simple way the parser is currently implemented. The ratio of importance to difficulty of implementation is such that I don't think I want to undertake this. I would be happy to accept a contribution of source code that would make the software do this, but I think it would be a big refactoring/rewrite, not a simple patch. As a workaround for this particular example, one could put a note on Thanksgiving saying, "Do X for Black Friday tomorrow." Thanks for your interest in When and for your suggestion. Sorry to have to reply unhelpully :-)
