### ISSUE TITLE
[Suggestion] Add week number to calendar

### ISSUE THREAD

**Issue by antoniocascais** [bcrowell/when#18]
Hello.

The program looks great, but there's a feature that's missing in my opinion: an option to show the week number in the calendar.

I looked at the docs and I didn't find it. Would it be too much to ask to add it?

**Comment by bcrowell** [comment]
Sorry, but this would complicated the code considerably, and I'm skeptical that many people would use such a feature.

**Comment by antoniocascais** [comment]
Fair enough. Thank you for getting back to me :)
