### ISSUE TITLE
Using GitHub's Releases for new versions of when

### ISSUE THREAD

**Issue by jansucan** [bcrowell/when#19]
Hello,

I would like to ask whether it would be possible to release new versions of `when` here at GitHub. Having `when` packed as a "standardized" archive (name-version) would make packaging work for distributions easier.

Best,
Jan

**Comment by bcrowell** [comment]
Hi -- Are you talking about some GitHub-specific feature, or just using "git tag"? If the former, could you point me to some info? If the latter, then that's super easy, and I can start doing that. By "archive," do you mean something like a zip file, which IIRC github automatically makes available if I use tags? By standardized, do you mean some naming convention for the zip file, which github would just do automatically by default?

**Comment by jansucan** [comment]
Yes, you have a correct idea. You can find info about the feature here:
https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

Few days ago I created a SlackBuild for Slackware (it's alredy in a [ready queue](https://slackbuilds.org/ready/)). A guy from there asked me, whether it would be possible to have a version included in the source archive.
Also, by publishing releases here would make the older versions easily available via stable links.

**Comment by bcrowell** [comment]
Cool, thanks for packaging this for slackware! I've done (I think) what you requested for version 1.1.39, and have added some notes to myself so this will be incorporated as a step in my workflow for future versions.

**Comment by jansucan** [comment]
Great! Thank you very much for your positive approach. :thumbsup:

I'm going to update the SlackBuild with a link to the new source archive.

**Comment by carnil** [comment]
@bcrowell btw thanks as well retrospectively from Debian downstream, this helps to remain on track and package new releases.

**Comment by bcrowell** [comment]
Hi,

On Wed, Dec 15, 2021 at 01:18:17PM -0800, carnil wrote:
> @bcrowell btw thanks as well retrospectively from Debian downstream,
> this helps to remain on track and package new releases.

Thanks for your work on packaging when for debian. I have already been
using github's releases for this purpose.

For example, the most recent release is this one:
https://github.com/bcrowell/when/releases/tag/1.1.41

  Ben
