### ISSUE TITLE
Unreproducible build due to timestamp in gzip header 

### ISSUE THREAD

**Issue by zhileiren** [bcrowell/when#22]
Hi!

While conducting a research in the spirit of the "reproducible builds" [1], we have noticed that the package "when" could not be built reproducibly, in that the gzip command is invoked without -n.

The attached patch removes timestamps when creating the archive. Once applied, the package can be built reproducibly.

[1]: https://wiki.debian.org/ReproducibleBuilds

[reproducible.diff.txt](https://github.com/bcrowell/when/files/5936038/reproducible.diff.txt)

**Comment by bcrowell** [comment]
Sorry, I don't understand what you mean by this. If you want to reopen this with more explanation, feel free to do so.

**Comment by zhileiren** [comment]
Sorry that I did not clarify the background. Reproducible builds are a set of software development practices that create an independently-verifiable path from source to binary code. More information could be found here [1]. Currently many software repositories such as Debian, Archlinux, and FreeBSD are actively conducting such practice. Actually this issue was found when I was doing some investigation for Archlinux packages.

As for the when package, the build is not reproducible because during the packaging stage, the command "gzip -9 <when.1 >when.1.gz" will embed a timestamp in when.1.gz. For instance, different md5sums were obtained in my experimental environment:

7dede0de1d305df1caac9b48d18241e9  control/source-root/pkg/when/usr/share/man/man1/when.1.gz
3978e00ebc392c6f88a6d7b1c8ec14be  experiment/source-root/pkg/when/usr/share/man/man1/when.1.gz

A common solution for such issue is to pass an "-n" argument to gzip [2], which prevents the timestamp embedding behavior.

[1] https://reproducible-builds.org/
[2] https://wiki.debian.org/ReproducibleBuilds/TimestampsInGzipHeaders

**Comment by anthraxx** [comment]
The goal is that no matter how often and when you rebuild the same application, all files that are packaged have exactly the same hashsum. This allows independent people to verify that the distributed packages are always bit by bit identical to what anyone else would build. It's part of the distro supply chain security.

**Comment by bcrowell** [comment]
Done.
