### ISSUE TITLE
query by date time interval

### ISSUE THREAD

**Issue by allanwind** [bcrowell/when#23]
The use case for --past/--future is that you run when at the start of your day (or precisely at exactly midnight) or you want to look at the same data repeatedly.  As you already parse time, it would be helpful if you could query by a date time interval to support the more general use case of running `when` at different times.  For instance, I prefer running it at 8pm this means that I either miss 4 hours if I use --past=1, or have to look through 2 days of data with --future=1.

ISO 8601 has 3 of 4 formats that might be be relevant (particular the first two):
```
<start>/<end>
<start>/<duration>
<end>/<duration>
```
where duration is:

```
PnYnMnDTnHnMnS
PnW
```

You could introduce a new option, say, --interval, that you would use like this:

--interval=$(date -d'' -Is)/P1D which would be --future=1
--interval=$(date -Is)/P1W from now (datetime) till next week

It could replace --past (which double negative usage is quirky and has to be explained in man page), --future, and --now.  Alternatively, you could allow --now to accept a timestamp and ensure that --past and --future respects that.  This still only gives you day granularity (so you cannot, say, give me a day and a half) but would solve the issue I have.

year (Y),  month (M) and week (W) are calendar calculations:

```
2021-1-31/P1Y is 2021-1-31 to 2022-1-31
2021-1-31/P1M is 2021-1-31 to 2021-1-28 (rolling back tot he last valid date)
```

It's best of the it's a half open time interval (from is inclusive, to is exclusive) as it allows you easily query non-overlapping data.

**Comment by bcrowell** [comment]
Part of the design decisions that went into the software are that it doesn't try to deal with times.
