### ISSUE TITLE
--noheader => --calendar_header & --items_header

### ISSUE THREAD

**Issue by allanwind** [bcrowell/when#24]
Please consider either replacing --[no]header or adding calendar and item specific header options.  The header doesn't add value for items (I know when I ran `when`, or the email from cron is already timestamped).  The header is most useful for the calendar output:

```
--[no]calendar_header
--[no]items_header
```

**Comment by bcrowell** [comment]
Part of the design decisions that went into the software is that it's easy to modify. You can just comment out the code that prints the calendar header.

**Comment by allanwind** [comment]
Here is the relevant diff in case anyone else looks for it:

diff --git a/when b/when
old mode 100644
new mode 100755
index 1de1465..7d7b51a
--- a/when
+++ b/when
@@ -1732,11 +1732,6 @@ sub normal_behavior {
   my $complete_output = '';
   my $lines_done = 2; # header and blank line under it
 
-  if ($preferences{'header'}) {
-    $complete_output = $complete_output . filter_accents_if_desired(describe_date())."\n\n"; 
-    $lines_done += 2; # header and blank line under it
-  }
-
   my @find_longest = (w('yesterday'),w('today'),w('tomorrow'));
   for (my $day_num=1; $day_num<=7; $day_num++) {
     push @find_longest,When::short_wday_name($day_num);
