### ISSUE TITLE
--[no]dayofweek tweak to output format

### ISSUE THREAD

**Issue by allanwind** [bcrowell/when#25]
I would like to hide the first column of the items output to make room for more of my calendar content, i.e.:

Tue        2021 May 26 Some long entry (like a url to our recycling schedule)

would like to make that just:

2021 May 26 Some long entry (like a url to our recycling schedule)

The wrapped would have to parse the command line to figure if it's calendar or items output, and if there is header.  By default it would be something like:

`
when "$@" |  sed '2,$s/.\{11\}//'`

**Comment by bcrowell** [comment]
Part of the design decisions that went into the software is that it's easy to modify. You can just comment out the code that prints the day of the week.
