### ISSUE TITLE
Customize date and time formats

### ISSUE THREAD

**Issue by allanwind** [bcrowell/when#26]
I would to be able to customize the format used for date (%F) and time (%H:%M) to be more compact and readable:

```
2021-05-25       A
2021-05-25 23:00 B
```

instead of the current:

```
Tue        2021 May 26 A
Tue        2021 May 26 01:00 B
```

See also #25.

**Comment by bcrowell** [comment]
Part of the design decisions that went into the software are that it doesn't try to deal with times.

**Comment by allanwind** [comment]
The man page says "Also affects the parsing of input times." about the --ampm option and there is a section "SORTING BY TIME OF DAY".
