### ISSUE TITLE
conform to XDG standards

### ISSUE THREAD

**Issue by xaltsc** [bcrowell/when#27]
Many people dislike having their `$HOME` cluttered. I am part of them.

Unfortunately, `when` only assumes that the preferences file is in `~/.when`, and even when provided with a `--calendar` option, refuses to do anything unless the file `~/.when/preferences` exists.

Two solutions to this problem are possible:

1. Try to find `${WHEN_CONFIG_HOME}/preferences` then `${XDG_CONFIG_HOME}/when/preferences` then `$HOME/.config/when/preferences` then `$HOME/.when/preferences` (or a variation thereof. Since there's only the `preferences` file to take into account, we could just use a variable `${WHEN_CONFIG}` which should be the path to this file).
2. Provide an option that ignores the existence of the `$HOME/.when/preference` file.

**Comment by xaltsc** [comment]
Another problem (but this should probably be another issue): `when` is totally unaware of the environment in the configuration file, calendars cannot be set with a variable.

**Comment by bcrowell** [comment]
Thanks for the suggestion. Done.

Re the second comment, the calendar is pointed to by a variable set in the preferences file.

**Comment by xaltsc** [comment]
Thanks for being so quick !

Quoting Ben crowell (2021-09-20 20:23:41)

**Comment by bcrowell** [comment]
I did almost zero testing, so if it doesn't work for your use case, please get back in touch.
