### ISSUE TITLE
unify erroring

### ISSUE THREAD

**Issue by quite** [bcrowell/when#29]
when outputs some errors to stderr, and exits with code -1, like:

```
Syntax error in calendar: 2021--foo
```

but some errors are output to stdout (with 6 asterixes), and exit code is 0, like:

```
****** Illegal day of the month: 2021 nov 31
******  2021 nov 31, foo
```

Both errors stops execution and no events are output, so it would be nice if at least non-zero exit code is set on all errors.

**Comment by bcrowell** [comment]
Thanks for pointing this out! I've made a version 1.1.42 that fixes the problem in the case you described (syntax errors in the calendar).
