### ISSUE TITLE
Yesterday's entries are lumped with today

### ISSUE THREAD

**Issue by msharov** [bcrowell/when#30]
when displays yesterday's appointments at the top of the list:
```
Tue 2021 Nov  9   8:48

yesterday  2021 Nov  8 Appointment 10:40am
today      2021 Nov  9 Appointment 10:00am
Thu        2021 Nov 11 Veterans Day
Thu        2021 Nov 11 Appointment 10:50am
```
"today" is highlighted in bold, but it is difficult to see where it starts. It would be better to either omit yesterday altogether (do I ever care what I had to do yesterday?), or add a blank line before today to clarify the start of the tasks I have not done yet.

**Comment by Mrfiregem** [comment]
From the man page:
```
--past=DAYS
               How many days into the past the report extends. Like the
               --future option, --past is interpreted as an offset relative to
               the present date, so normally you would want this to be a
               negative value. Default: -1
```
You can alias when to `when --past=0`.

**Comment by bcrowell** [comment]
When is a single fairly short perl file, designed to be easy to tinker with. If you want the word "yesterday" not to appear, it should be simple to achieve this by modifying the source.
