### ISSUE TITLE
Could it be possible to schedule an item every 'x' days?

### ISSUE THREAD

**Issue by pierostrada** [bcrowell/when#33]
Hello there - and true congrats for 'github.com/bcrowell/when'.
First of all, please forgive me if I'm doing anything wrong - it's my very first time here.

My question is: Could it be possible to schedule an item every 'x' days?
For instance: (magic-formula-with 30_days-from-YYYY MM DD), Pay your ISP bill

Maybe it's already possible and I did not get it.
Maybe it's possible using the julian date function.

Maybe I'm dumb...
Thanks for your attention and patience, Piero

**Comment by bcrowell** [comment]
Yes, this can be done with the j variable and the % operator. There is a similar example in the man page. Look for "do something every other Wednesday".
