### ISSUE TITLE
termux

### ISSUE THREAD

**Issue by ralmcruz** [bcrowell/when#35]
Tryied to install on termux on Android but got this:

Is there another way to install?
----

perl -e 'open(F,"<when") or die "file not found"; local $/; $code = <F>; close F; open(F,">temp") or die "error writing"; print F "#!".`which perl`."\n$code"; close F;'
# ... make sure it starts with the proper #! line, regardless of whether we're on Linux, BSD, etc.
test -d /usr/bin || mkdir -p /usr/bin
mkdir: cannot create directory ‘/usr’: Read-only file system
make: [Makefile:46: install] Error 1 (ignored)
# ... if the intended directory doesn't exist, create it
install -m 755 temp /usr/bin/when
install: cannot create regular file '/usr/bin/when': No such file or directory
make: *** [Makefile:48: install] Error 1

----

**Comment by bcrowell** [comment]
The program doesn't care what directory it's installed in. Just copy the file to any directory where you have privileges and that's in your path.
