### ISSUE TITLE
"last day of the month" test?

### ISSUE THREAD

**Issue by dmfay** [bcrowell/when#36]
hi, thanks for when! I want to add a reminder for the final day of each month but can't find an obvious solution (`d=-1` yields September 1 next) and am not sure whether I can make the fancy-tests math work for me. Is there a way to do this?

**Comment by bcrowell** [comment]
This is what the b variable is for.

**Comment by dmfay** [comment]
`b=1, test` yields this:

```
Thu        2022 Aug 25 test
Fri        2022 Aug 26 test
Sat        2022 Aug 27 test
Sun        2022 Aug 28 test
Mon        2022 Aug 29 test
Tue        2022 Aug 30 test
Wed        2022 Aug 31 test
```

I'm trying to get _just_ August 31, September 30, October 31, etc. Available combinations allow last $day-of-week in a month and the like but the best I've got right now is `b=1 & d >=28` to accommodate February, where `b` isn't actually adding anything since all days >= 28 are in the last week of a month already.

**Comment by bcrowell** [comment]
Oops, sorry, I forgot how my own software works!

I've released a new version that has a variable n in it for the number of days in the month. To get the test for the last day of the month, use d=n.

Thanks for bearing with me and for helping me to improve the software.
