### ISSUE TITLE
WHEN_CONFIG_HOME issue

### ISSUE THREAD

**Issue by audiofool** [bcrowell/when#38]
I can't seem to get WHEN_CONFIG_HOME or XDG_CONFIG_HOME to work always asks for the defaults to be set up.  
Could a command line option be added to ignore requiring preferences file and when directory?
Thanks again!

**Comment by bcrowell** [comment]
Sorry, this isn't enough information for me to understand what problem you're encountering.

**Comment by audiofool** [comment]
Setting WHEN_CONFIG_HOME or XDG_CONFIG_HOME seems to be ignored by 'when'
'when' still asks to create ~/.when

From shell:
export WHEN_CONFIG_HOME="~/mycustomdir"
mkdir "${WHEN_CONFIG_HOME}"
touch "${WHEN_CONFIG_HOME}/preferences"
when => You can now set up your calendar. This involves creating a directory ~/.when

Also, Could a command line option be added to ignore requiring preferences file and when directory?

**Comment by bcrowell** [comment]
I see. It's not ignoring the environment variable. The message "...creating a directory ~/.when" is just a canned message where "~/.when" is a hardcoded string.

**Comment by audiofool** [comment]
Thanks, it works.  What was throwing me was that 'when c' works with the default directory and an empty preferences file but requires --calendar when using WHEN_CONFIG_HOME
Much appreciated.
