### ISSUE TITLE
Feb 29 is not accepted

### ISSUE THREAD

**Issue by a1s** [bcrowell/when#6]
If a calendar file contains an event on February, 29th, when complains on invalid date:

****** Illegal day of the month: * Feb 29
******  * Feb 29 , Birthday: John

**Comment by bcrowell** [comment]
Thanks for the bug report. I've fixed it in when 1.1.35. This was actually a bug in handling the wildcard date "* feb 29", not a bug in handling non-wildcard dates such as "2016 feb 29".

**Comment by a1s** [comment]
It works now.  Thank you!
