### ISSUE TITLE
variable "neighboring_months" ignored in file "~/.when/preferences"

### ISSUE THREAD

**Issue by jeremy-ox** [bcrowell/when#7]
Try to insert following line to file "~/.when/preferences":

```
neighboring_months = no
```

when run
```bash
when c
```

Actual result: `when` will print three months calendar.
Expected result: print one month calendar, like
```
when c --noneighboring_months
```
does.

**Comment by bcrowell** [comment]
Thanks for your interest in When. As described in the documentation, boolean preferences are set using 0 and 1, not words like yes and no.
