### ISSUE TITLE
feature request: date-interval

### ISSUE THREAD

**Issue by drzraf** [bcrowell/when#8]
I use when for years and this is something I miss:
I didn't find a way to "restrict" a regular event to a start date and an end date.
Eg:
during the 3 nexts months reunion at 11h the mondays
``y=2015 & w=mon & m >= 4 & m < 9,  11h meeting``
If we have multiple of the type it start to be hard to read.
Not even speaking about the case where the event is cancelled once or twice (that add even more complexity).
Could we consider an alternative notation for such events

Here is a suggestion (but alternatives may exists): a "D" variable representing the whole day and supporting "=", "!=", ">" and "<" comparison operator:
``<standard syntax> & D > DATE1 & D < DATE2``
Example:
``w=mon & D > 2015/04/01 & D < 2015/09/15, 11h meeting``
Adding an exception could be as "simple" as:
``w=mon & D > 2015/04/01 & D < 2015/09/15 & D !=  2015/08/06, 11h meeting``

**Comment by bcrowell** [comment]
Thanks for the suggestion, but this would not be straightforward to implement, and I don't think the benefits would be in proportion to the amount of work required.
