### ISSUE TITLE
feature request: recurring from a custom starting date

### ISSUE THREAD

**Issue by drzraf** [bcrowell/when#9]
This my second most missed feature for when:
It sometimes happens that one have an event every two weeks.

Contrary to events month-based (last Sunday of the month, second Tuesday of the month, which are nicely handled with current variables), this can't be easily handled with current operators because the "base day" for the recurrence could be any date ("j" and "z" comes to the rescue)

Eg: ``since the 2016/04/11, monday : go to the psy ... and then every 2 weeks``
An expression based on "z" would be : ``y=2016 & z >= 107 & !((z-107)%14)`` (2016/04/11 being 107)

But given this kind of recurrence is based on days in most case, don't you think the feature is useful enough to justify adding another variable and/or syntax?
Example: ``D >= 2016/04/11 & 2016/04/11 % 14``?
(see also issue #8)

**Comment by bcrowell** [comment]
Thanks for the suggestion. This would be complicated to implement, and I perceive the added benefit as not being in proportion to the added work.
